name: Deploy NestJS to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Upload files via FTP
        uses: appleboy/ftp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}       # cpanel.rittikbansal.com
          username: ${{ secrets.CPANEL_USER }}   # your FTP username
          password: ${{ secrets.CPANEL_PASS }}   # your FTP password
          port: 21                               # FTP port
          protocol: ftp                          # use ftp or ftps if supported
          local-dir: "dist"                      # folder to upload
          remote-dir: "/www/wwwroot/saasCrm_backend-test"
          delete: true                           # optional: remove old files first
          passive: true                          # usually needed for external FTP
